In [37]:
import pandas as pd
import numpy as np

In [38]:
nfhs = pd.read_csv("../Datasets/Processed_Data/NFHS_Clean.csv")

doctors = pd.read_csv("../Datasets/Processed_Data/RHS/Doctors_Clean.csv")

specialists = pd.read_csv("../Datasets/Processed_Data/RHS/Specialists_Clean.csv")

nursing = pd.read_csv("../Datasets/Processed_Data/RHS/Nursing_Clean.csv")

facilities = pd.read_csv("../Datasets/Processed_Data/RHS/Facilities_Clean.csv")

shortfall = pd.read_csv("../Datasets/Processed_Data/RHS/Shortfall_Clean.csv")

mmr = pd.read_csv("../Datasets/Processed_Data/SRS/MMR_Clean.csv")

mmr_trend = pd.read_csv("../Datasets/Processed_Data/SRS/MMR_Trend_Clean.csv")

age_distribution = pd.read_csv("../Datasets/Processed_Data/SRS/Age_Distribution_Clean.csv")


In [39]:
print(nfhs.columns)
print(doctors.columns)
print(specialists.columns)
print(nursing.columns)
print(facilities.columns)
print(shortfall.columns)
print(mmr.columns)

Index(['State', 'ANC_First', 'ANC_4', 'PNC_2Days', 'Delivery_Cost',
       'Institutional_Delivery', 'CSection_Rate'],
      dtype='str')
Index(['State_UT', '2022_Required', '2022_Sanctioned', '2022_InPosition',
       '2022_Vacant', '2022_Shortfall'],
      dtype='str')
Index(['State_UT', '2022_Required', '2022_Sanctioned', '2022_InPosition',
       '2022_Vacant', '2022_Shortfall'],
      dtype='str')
Index(['State_UT', '2022_Required', '2022_Sanctioned', '2022_InPosition',
       '2022_Vacant', '2022_Shortfall'],
      dtype='str')
Index(['State_UT', 'SubCentres_Rural', 'SubCentres_Urban', 'PHCs_Rural',
       'PHCs_Urban', 'CHCs_Rural', 'CHCs_Urban'],
      dtype='str')
Index(['State_UT', 'SC_Required', 'SC_InPosition', 'SC_Shortfall',
       'SC_PctShortfall', 'PHC_Required', 'PHC_InPosition', 'PHC_Shortfall',
       'PHC_PctShortfall', 'CHC_Required', 'CHC_InPosition', 'CHC_Shortfall',
       'CHC_PctShortfall'],
      dtype='str')
Index(['State_Group', 'MMR', 'CI_Lower', 'CI_Uppe

In [40]:
doctors.rename(columns={"State_UT": "State"}, inplace=True)

specialists.rename(columns={"State_UT": "State"}, inplace=True)

nursing.rename(columns={"State_UT": "State"}, inplace=True)

facilities.rename(columns={"State_UT": "State"}, inplace=True)

shortfall.rename(columns={"State_UT": "State"}, inplace=True)

mmr.rename(columns={"State_Group": "State"}, inplace=True)

In [41]:
print(nfhs.columns)
print(doctors.columns)
print(mmr.columns)

Index(['State', 'ANC_First', 'ANC_4', 'PNC_2Days', 'Delivery_Cost',
       'Institutional_Delivery', 'CSection_Rate'],
      dtype='str')
Index(['State', '2022_Required', '2022_Sanctioned', '2022_InPosition',
       '2022_Vacant', '2022_Shortfall'],
      dtype='str')
Index(['State', 'MMR', 'CI_Lower', 'CI_Upper', 'Maternal_Mortality_Rate',
       'Lifetime_Risk_Pct'],
      dtype='str')


In [42]:
set(nfhs["State"]) - set(doctors["State"])

{'Andaman & Nicobar Islands',
 'Dadra & Nagar Haveli and Daman & Diu',
 'India',
 'NCT Delhi'}

In [43]:
set(doctors["State"]) - set(nfhs["State"])

{'A & N Islands', 'All India Total', 'D & N Haveli', 'Daman & Diu', 'Delhi'}

In [44]:
set(mmr["State"]) - set(nfhs["State"])

{'EAG AND ASSAM SUBTOTAL',
 'INDIA',
 'OTHER SUBTOTAL',
 'Other states',
 'SOUTH SUBTOTAL'}

In [45]:
doctors["State"] = doctors["State"].replace({
    "A & N Islands": "Andaman & Nicobar Islands",
    "Delhi": "NCT Delhi",
    "All India Total": "India"
})

specialists["State"] = specialists["State"].replace({
    "A & N Islands": "Andaman & Nicobar Islands",
    "Delhi": "NCT Delhi",
    "All India Total": "India"
})

nursing["State"] = nursing["State"].replace({
    "A & N Islands": "Andaman & Nicobar Islands",
    "Delhi": "NCT Delhi",
    "All India Total": "India"
})

facilities["State"] = facilities["State"].replace({
    "A & N Islands": "Andaman & Nicobar Islands",
    "Delhi": "NCT Delhi",
    "All India Total": "India"
})

shortfall["State"] = shortfall["State"].replace({
    "A & N Islands": "Andaman & Nicobar Islands",
    "Delhi": "NCT Delhi",
    "All India Total": "India"
})

In [46]:
mmr = mmr[
    ~mmr["State"].isin([
        "INDIA",
        "EAG AND ASSAM SUBTOTAL",
        "SOUTH SUBTOTAL",
        "OTHER SUBTOTAL",
        "Other states"
    ])
]

In [47]:
set(nfhs["State"]) - set(doctors["State"])


{'Dadra & Nagar Haveli and Daman & Diu'}

In [48]:
set(doctors["State"]) - set(nfhs["State"])

{'D & N Haveli', 'Daman & Diu'}

In [49]:
master = pd.merge(
    nfhs,
    doctors,
    on="State",
    how="left"
)

In [50]:
master.shape

(37, 12)

In [51]:
master.head()

,State,ANC_First,ANC_4,PNC_2Days,Delivery_Cost,Institutional_Delivery,CSection_Rate,2022_Required,2022_Sanctioned,2022_InPosition,2022_Vacant,2022_Shortfall
0,Andaman & Nicobar Islands,77.1,83.4,88.9,2924.0,99.0,29.9,22.0,53,50,3,*
1,Andhra Pradesh,81.7,67.5,90.7,3105.0,96.5,42.4,1142.0,2206,2048,158,*
2,Arunachal Pradesh,53.1,36.5,56.4,9731.0,79.2,14.8,126.0,NaN,129,NaN,*
3,Assam,63.8,50.7,65.3,5415.0,84.1,18.1,920.0,1617,1381,236,*
4,Bihar,52.9,25.2,57.3,2848.0,76.2,9.7,1492.0,3595,1538,2057,*


In [52]:
master.info()

<class 'pandas.DataFrame'>
RangeIndex: 37 entries, 0 to 36
Data columns (total 12 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   State                   37 non-null     str    
 1   ANC_First               37 non-null     float64
 2   ANC_4                   37 non-null     float64
 3   PNC_2Days               37 non-null     float64
 4   Delivery_Cost           37 non-null     float64
 5   Institutional_Delivery  37 non-null     float64
 6   CSection_Rate           37 non-null     float64
 7   2022_Required           36 non-null     float64
 8   2022_Sanctioned         34 non-null     str    
 9   2022_InPosition         36 non-null     str    
 10  2022_Vacant             34 non-null     str    
 11  2022_Shortfall          36 non-null     str    
dtypes: float64(7), str(5)
memory usage: 3.6 KB


In [53]:
master[master["2022_Required"].isnull()][["State"]]

,State
7,Dadra & Nagar Haveli and Daman & Diu


In [54]:
master = pd.merge(
    master,
    specialists,
    on="State",
    how="left"
)

In [55]:
master.shape

(37, 17)

In [56]:
master[master["2022_Required_y"].isnull()][["State"]]

,State
7,Dadra & Nagar Haveli and Daman & Diu


In [57]:
master = pd.merge(
    master,
    nursing,
    on="State",
    how="left"
)

In [58]:
master.shape

(37, 22)

In [59]:
master.columns

Index(['State', 'ANC_First', 'ANC_4', 'PNC_2Days', 'Delivery_Cost',
       'Institutional_Delivery', 'CSection_Rate', '2022_Required_x',
       '2022_Sanctioned_x', '2022_InPosition_x', '2022_Vacant_x',
       '2022_Shortfall_x', '2022_Required_y', '2022_Sanctioned_y',
       '2022_InPosition_y', '2022_Vacant_y', '2022_Shortfall_y',
       '2022_Required', '2022_Sanctioned', '2022_InPosition', '2022_Vacant',
       '2022_Shortfall'],
      dtype='str')

In [60]:
master.rename(columns={
    # Doctors
    "2022_Required_x": "Doctors_Required",
    "2022_Sanctioned_x": "Doctors_Sanctioned",
    "2022_InPosition_x": "Doctors_InPosition",
    "2022_Vacant_x": "Doctors_Vacant",
    "2022_Shortfall_x": "Doctors_Shortfall",

    # Specialists
    "2022_Required_y": "Specialists_Required",
    "2022_Sanctioned_y": "Specialists_Sanctioned",
    "2022_InPosition_y": "Specialists_InPosition",
    "2022_Vacant_y": "Specialists_Vacant",
    "2022_Shortfall_y": "Specialists_Shortfall",

    # Nursing
    "2022_Required": "Nursing_Required",
    "2022_Sanctioned": "Nursing_Sanctioned",
    "2022_InPosition": "Nursing_InPosition",
    "2022_Vacant": "Nursing_Vacant",
    "2022_Shortfall": "Nursing_Shortfall"
}, inplace=True)

In [61]:
master.columns

Index(['State', 'ANC_First', 'ANC_4', 'PNC_2Days', 'Delivery_Cost',
       'Institutional_Delivery', 'CSection_Rate', 'Doctors_Required',
       'Doctors_Sanctioned', 'Doctors_InPosition', 'Doctors_Vacant',
       'Doctors_Shortfall', 'Specialists_Required', 'Specialists_Sanctioned',
       'Specialists_InPosition', 'Specialists_Vacant', 'Specialists_Shortfall',
       'Nursing_Required', 'Nursing_Sanctioned', 'Nursing_InPosition',
       'Nursing_Vacant', 'Nursing_Shortfall'],
      dtype='str')

In [62]:
master = pd.merge(
    master,
    facilities,
    on="State",
    how="left"
)

In [63]:
master.shape

(37, 28)

In [64]:
master = pd.merge(
    master,
    shortfall,
    on="State",
    how="left"
)

In [65]:
master.shape

(37, 40)

In [66]:
master = pd.merge(
    master,
    mmr,
    on="State",
    how="left"
)

In [67]:
master.shape

(37, 45)

In [68]:
master.isnull().sum()

State                       0
ANC_First                   0
ANC_4                       0
PNC_2Days                   0
Delivery_Cost               0
Institutional_Delivery      0
CSection_Rate               0
Doctors_Required            1
Doctors_Sanctioned          3
Doctors_InPosition          1
Doctors_Vacant              3
Doctors_Shortfall           1
Specialists_Required        1
Specialists_Sanctioned      5
Specialists_InPosition      1
Specialists_Vacant          5
Specialists_Shortfall       1
Nursing_Required            1
Nursing_Sanctioned          3
Nursing_InPosition          1
Nursing_Vacant              3
Nursing_Shortfall           1
SubCentres_Rural            1
SubCentres_Urban            1
PHCs_Rural                  1
PHCs_Urban                  1
CHCs_Rural                  1
CHCs_Urban                  1
SC_Required                 1
SC_InPosition               1
SC_Shortfall                1
SC_PctShortfall             1
PHC_Required                1
PHC_InPosi

In [69]:
master.replace("*", np.nan, inplace=True)
master.to_csv("Maternal_Health_Clean.csv", index=False)

In [70]:
for col in master.columns:
    print(col)
    print(master[col].unique()[:10])
    print("-" * 50)

State
<StringArray>
[           'Andaman & Nicobar Islands',
                       'Andhra Pradesh',
                    'Arunachal Pradesh',
                                'Assam',
                                'Bihar',
                           'Chandigarh',
                         'Chhattisgarh',
 'Dadra & Nagar Haveli and Daman & Diu',
                                  'Goa',
                              'Gujarat']
Length: 10, dtype: str
--------------------------------------------------
ANC_First
[77.1 81.7 53.1 63.8 52.9 82.3 65.7 77.7 70.3 79.3]
--------------------------------------------------
ANC_4
[83.4 67.5 36.5 50.7 25.2 78.7 60.1 86.2 93.  76.9]
--------------------------------------------------
PNC_2Days
[88.9 90.7 56.4 65.3 57.3 90.6 84.  91.6 95.4 89.7]
--------------------------------------------------
Delivery_Cost
[2924. 3105. 9731. 5415. 2848. 5546. 1833.  677. 3804. 1697.]
--------------------------------------------------
Institutional_Delivery
[99.  96.5 

In [71]:
master.select_dtypes(include="object").head()

C:\Users\anmol_krrh5y2\AppData\Local\Temp\ipykernel_26640\2353045947.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  master.select_dtypes(include="object").head()


,State,Doctors_Sanctioned,Doctors_InPosition,Doctors_Vacant,Doctors_Shortfall,Specialists_Sanctioned,Specialists_InPosition,Specialists_Vacant,Specialists_Shortfall,Nursing_Sanctioned,...,SC_Shortfall,SC_PctShortfall,PHC_Required,PHC_InPosition,PHC_Shortfall,PHC_PctShortfall,CHC_Required,CHC_InPosition,CHC_Shortfall,CHC_PctShortfall
0,Andaman & Nicobar Islands,53,50,3,NaN,16,4,12,12,158,...,NaN,NaN,7,22,NaN,NaN,1,4,NaN,NaN
1,Andhra Pradesh,2206,2048,158,NaN,408,264,144,292,4630,...,NaN,NaN,1167,1142,25,2,291,139,152,52
2,Arunachal Pradesh,NaN,129,NaN,NaN,NaN,11,NaN,217,NaN,...,NaN,NaN,52,126,NaN,NaN,13,57,NaN,NaN
3,Assam,1617,1381,236,NaN,267,179,88,509,3484,...,1879,29,1068,920,148,14,267,172,95,36
4,Bihar,3595,1538,2057,NaN,1281,322,959,754,8223,...,12863,58,3698,1492,2206,60,924,269,655,71


In [73]:
for col in master.columns:
    if col != "State":
        master[col] = pd.to_numeric(master[col], errors="coerce")

In [74]:
master.dtypes

State                          str
ANC_First                  float64
ANC_4                      float64
PNC_2Days                  float64
Delivery_Cost              float64
Institutional_Delivery     float64
CSection_Rate              float64
Doctors_Required           float64
Doctors_Sanctioned         float64
Doctors_InPosition         float64
Doctors_Vacant             float64
Doctors_Shortfall          float64
Specialists_Required       float64
Specialists_Sanctioned     float64
Specialists_InPosition     float64
Specialists_Vacant         float64
Specialists_Shortfall      float64
Nursing_Required           float64
Nursing_Sanctioned         float64
Nursing_InPosition         float64
Nursing_Vacant             float64
Nursing_Shortfall          float64
SubCentres_Rural           float64
SubCentres_Urban           float64
PHCs_Rural                 float64
PHCs_Urban                 float64
CHCs_Rural                 float64
CHCs_Urban                 float64
SC_Required         

In [75]:
master.to_csv(
    "../Datasets/Master_Data/Maternal_Health_Master_Dataset.csv",
    index=False
)

In [76]:
master.select_dtypes(include="object").columns

C:\Users\anmol_krrh5y2\AppData\Local\Temp\ipykernel_26640\1587831797.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  master.select_dtypes(include="object").columns


Index(['State'], dtype='str')

In [77]:
master.to_csv("../Datasets/Maternal_Health_Clean.csv", index=False)